import { Datetime_global } from "./Datetime_global.js";
import { Temporal } from "temporal-polyfill";
import { ClockTime } from "./RelativeTimeChecker.js";
export declare class ClockDate extends ClockTime {
    validateDate(): Date | null;
    set minutesAfterMidnight(value: unknown);
    get minutesAfterMidnight(): number | null;
    set timezoneId(value: unknown);
    get timezoneId(): string | null;
    set date(value: unknown);
    get date(): Date | null;
    toDate(): Date | null;
    withTimezone(timezone: string): Datetime_global;
    toTimezone(timezone: string): Datetime_global;
    getTimezoneId(): string;
    valueOf(): number;
    getTime(): number;
    setTime(time: number): number;
    toString(): string;
    toHTML(): never;
    toHTMLFormatted(): never;
    toHTML_GMT(): never;
    toHTML_UTC(): never;
    toHTMLHistoryString(): never;
    toHTMLString(): never;
    getDay(): number;
    getDayOfWeek(): number;
    getYear(): number;
    getFullYear(): number;
    getMonth(): number;
    getDate(): number;
    getHours(): number;
    getMinutes(): number;
    getSeconds(): number;
    getMilliseconds(): number;
    getUTCDay(): number;
    getUTCYear(): number;
    getUTCFullYear(): number;
    getUTCMonth(): number;
    getUTCDate(): number;
    getUTCHours(): number;
    getUTCMinutes(): number;
    getUTCSeconds(): number;
    getUTCMilliseconds(): number;
    getTimezoneOffset(): number;
    toISOString(): string | null;
    toJSON(): string | null;
    setFullYear(fullYear: number, month?: number, date?: number): number | null;
    setMonth(month: number, date?: number): number | null;
    setDate(date: number): number | null;
    setHours(hours: number, minutes?: number, seconds?: number, milliseconds?: number): number | null;
    setMinutes(minutes: number, seconds?: number, milliseconds?: number): number | null;
    setSeconds(seconds: number, milliseconds?: number): number | null;
    setMilliseconds(milliseconds: number): number | null;
    setUTCFullYear(fullYear: number, month?: number, date?: number): number | null;
    setUTCHours(hours: number, minutes?: number, seconds?: number, milliseconds?: number): number | null;
    setUTCMonth(month: number, date?: number): number | null;
    setUTCDate(date: number): number | null;
    setUTCMinutes(minutes: number, seconds?: number, milliseconds?: number): number | null;
    setUTCSeconds(seconds: number, milliseconds?: number): number | null;
    toTemporalZonedDateTime(): Temporal.ZonedDateTime | null;
    setNanoseconds(): void;
    getNanoseconds(): void;
    getUTCNanoseconds(): void;
    toUTCTimezone(): Datetime_global;
    toLocalTime(): Datetime_global;
    getDayNumberWeek(): number;
    getDayNumber(): number;
    getDayNumberMonth(): number;
    getDayName(): string;
    getMonthName(): string;
    getFullDayName(): string;
    getFullMonthName(): string;
    toLocaleString(locales?: string | string[] | undefined, options?: Intl.DateTimeFormatOptions | undefined): string;
    toGMTString(): string | null;
    toUTCString(): string | null;
    toDateString(): string | null;
    toTimeString(): string | null;
    format(): never;
    templateFormat(): never;
    withCalender(): never;
    clone(): void;
    startOfDay(timezone?: string): Datetime_global;
    getTimestamp(): bigint | null;
    until(): void;
    since(): void;
}
//# sourceMappingURL=ClockDate.d.ts.map